apiVersion: v1
kind: Secret
metadata:
  name: dvwa-db
  labels:
    app: dvwa
    component: database
data:
  DATABASE_USER: ZHZ3YQ==              # echo -n 'dvwa'|base64
  DATABASE_PASSWORD: UEBzc3cwcmQ=      # echo -n 'P@ssw0rd'|base64
type: Opaque
