apiVersion: v1
kind: Service
metadata:
  name: dvwa-db
  labels:
    app: dvwa
    component: database
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: mariadb
  selector:
    app: dvwa
    component: database
