apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-web
  labels:
    app: dvwa
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
      component: web
  template:
    metadata:
      labels:
        app: dvwa
        component: web
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: dvwa
          image: harbor.ptdemo.local/applications/dvwa:2.3.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 80
          env:
          - name: DATABASE_SERVER
            valueFrom:
              configMapKeyRef:
                name: dvwa
                key: DATABASE_SERVER
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: dvwa
                key: DATABASE_PORT
                optional: true
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: dvwa
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: dvwa-db
                key: DATABASE_USER
                optional: true
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dvwa-db
                key: DATABASE_PASSWORD
                optional: true
          - name: DISABLE_AUTHENTICATION
            valueFrom:
              configMapKeyRef:
                name: dvwa
                key: DISABLE_AUTHENTICATION
                optional: true
          - name: DEFAULT_SECURITY_LEVEL
            valueFrom:
              configMapKeyRef:
                name: dvwa
                key: DEFAULT_SECURITY_LEVEL
                optional: true
          securityContext:
            capabilities:
              add:
                - NET_RAW
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      restartPolicy: Always