apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvwa-ingress
  namespace: ptdemo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: dvwa.ptdemo.local 
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: dvwa-service
            port:
              number: 80
