apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: ptdemo
spec:
  selector:
    app: dvwa-server
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
